linters:
  pep8:
    python: 3
    max-line-length: 120
    fixer: true
    ignore:
      - 'W28'
      - 'W504'
      - 'E128'
      - 'E501'
      - 'E122'
      - 'W503'
fixers:
  enable: true
review:
  fail_on_comments: false
files:
    ignore:
        - 'docs/**/*'
        - 'monet/data/*'
